import Header from '@/components/Header';
// Fonts
import { Nunito } from 'next/font/google';
// Styles
import './globals.css';

const nunito = Nunito({
  weight: ['400', '700'],
  subsets: ['latin']
});

export const metadata = {
  title: 'Next.js crash course',
  description: 'Generated by create next app',
  keywords: 'web development, react, next, javascript, typescript'
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => (
  <html lang="en">
    <body className={nunito.className}>
      <Header />
      <main className='container'>
        {children}
      </main>
    </body>
  </html>
);

export default RootLayout;